# Generated by Django 5.1.2 on 2026-03-02 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0001_initial"),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the application's logo image (displayed on login/register screens).",
                        max_length=500,
                    ),
                ),
                (
                    "brand_color",
                    models.CharField(
                        blank=True,
                        help_text="Primary brand hex color (e.g. #1C352D) used for buttons and accents.",
                        max_length=7,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Branding",
                "verbose_name_plural": "Application Brandings",
            },
        ),
    ]
