# Generated by Django 5.1.2 on 2026-03-02 12:38

import modules.entities.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0002_move_branding_from_standalone_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationbranding",
            name="brand_color",
            field=models.CharField(
                blank=True,
                help_text="Primary brand hex color (e.g. #1C352D) used for buttons and accents.",
                max_length=7,
                validators=[modules.entities.models.validate_hex_color],
            ),
        ),
    ]
