[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = src .
addopts = -n auto --cov=src --cov-report=term-missing --no-cov-on-fail
filterwarnings =
    ignore:.*urllib3.*
    ignore:.*RequestsDependencyWarning.*

[pytest-env]
SECURE_SSL_REDIRECT=False
OIDC_RSA_PRIVATE_KEY=dummy
